### PR TITLE
Stage 2 - Submission for review

### PR DESCRIPTION
**Pull request by lindakovacs**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Linda!

Amazing job! Some corrections need to be made, but on the whole, the project is very impressive!

Please, note that the dev version fails to compile: https://prnt.sc/12ic36i

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* A horizontal scroll on all resolutions: https://prnt.sc/12ic51u
* Footer content isn't centered
* Incorrect line-height: https://prnt.sc/12ic93u
* On mobile screens: https://prnt.sc/12icido
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
* Incorrect layout of a card and horizontal scroll: https://prnt.sc/12iccr8. Please, check the card layout on all resolutions from 320 to big desktop screens
* Content is outside the container: https://prnt.sc/12icfzx
* https://prnt.sc/12icjc3
- [ ]  There are no validation errors.
https://prnt.sc/12icveu
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.
- Sign up popup, Registration successfull popup

- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [x]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [ ]  System fonts are connected as alternatives to each of your fonts.
Please find and correct all similar cases: https://prnt.sc/12id38w
- [ ]  Raster and vector images have been optimized.

## Number of points: 62

**Comment by ImaliaNsk** [comment]
Great job, almost ready! A few remarks about the responsive layout are left:

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* A horizontal scroll on all resolutions: https://prnt.sc/12ic51u. Please pay the closest attention to your `main` block and how you assign width for it.
* A horizontal scroll on mobile screens, the footer doesn't fit in the container: https://prnt.sc/12r3nqm
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.
* Redundant side margin: https://prnt.sc/12r3x0w, causes a horizontal scroll
* Footer is too narrow for the screen width, should have the same width and other sections: https://prnt.sc/12r3z77
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [x]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Raster and vector images have been optimized.

## Number of points: 70

**Comment by ImaliaNsk** [comment]
Hi! Great job, the project is accepted. Good luck on the next stage. Please, note that there's a small horizontal scroll left on mobile screens because of footer, the content doesn't fit inside the container.

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
* A horizontal scroll on mobile screens (320 - 335), the footer doesn't fit in the container: https://prnt.sc/12sddhh. https://prnt.sc/12sdeh4
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [x]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [ ]  Raster and vector images have been optimized.

## Number of points: 

## Additional comments: 84

**Comment by lindakovacs** [comment]
@ImaliaNsk thank you so much for your feedback across the projects. It was such a pleasure to work with you. I will check the footer and fix it after office hours and then resubmit it.

**Comment by lindakovacs** [comment]
@ImaliaNsk I just push the code to fix the footer issue but I realized that I can't submit the link for review. Could you please take a look into it? Thank you

**Comment by ImaliaNsk** [comment]
@lindakovacs Hi! Looks good, the scroll is gone and the content stays inside the container. You can consider your score to be 99/100, that's a great result! Wish you good luck on the next stage!

**Comment by lindakovacs** [comment]
@ImaliaNsk Thank you so much for your feedback! I had to fix it for the next stage anyways.

**Pull request merged**
