### PR TITLE
Stage 3

### PR DESCRIPTION
**Pull request by lindakovacs**

### CODE REVIEW

**Comment by arinaward** [comment]
Hello, Linda. Unfortunately, your project can't be reviewed due to the fact that the functionality required for this stage does not work, the cards are not loading to the page even though request to the backend is successfull and returns the correct data, also getting the error when trying to signup. Please see attached screenshots: https://paste.pics/3beab2023baed807587081afb3bb892e
https://paste.pics/c597b197f10ead0462fc4f6d3c7890cd

In order to fix the signup error the frontend must be configured to work with a backend located on the server, now the project is configured to work with localhost

Please configure the project to work with a backend on the server, thanks 🌺

**Comment by arinaward** [comment]
Hello! Thank you so much for submitting your project, I can see that you've put a lot of work into this. There are a few things that need to be done before your project can be accepted. Please take a look at the comments below. Hope it will be easy to fix

# Summary:
### Performance Criteria

- [ ]  The project functionality is fully implemented according to the current stage's requirements:
    - The preloader is visible and spinning during request execution. 
    - All project links and buttons are functioning. 
    - All forms are validated on the client side. 
    _COMMENT_:
	**When the search form is submitted, it should be validated. If no text is entered in the field, the error "Please enter a keyword" should be displayed OR search button should also be disabled if nothing was entered in the search field. Currently, if no text was entered no errors are displayed, you also add an empty value to localStorage and the input is disabled in this case which makes it impossible to enter a new value without page reload**
    - When clicking on the "Sign up" button in the "Sign up" popup window, a request is sent to the `/signup` route, provided that all input fields have been filled in correctly. If the request is successful, a message is displayed.
    - When clicking on the "Sign up" button in the "Sign up" popup window, a request is sent to the `/signup` route, provided that all input fields have been filled in correctly. If the request is successful, a message is displayed.
    - When clicking on the "Sign in" button, provided that all input fields have been filled in correctly, a request is sent to the `/signin` route. If the request is successful, the popup is closed.
    - Both header states function correctly. If the user is not logged in, the header should have the "Sign in" button; and if the user is logged in, there should be no "Sign in" button. The "Saved articles" link, along with a log out button, should appear in its place.
    - Once the search form has been submitted successfully, a block with results appears. If nothing was found, the message "Nothing found" appears.
    _COMMENT_:
    **If the user is logged in and trying to execute the search, the response is sent to the backed and correct data is returned, but the preloader is still spinning and no cards are shown: https://snipboard.io/ocWrv7.jpg**
    - 3 cards are displayed in the results block. Clicking on the "Show more" button will render the next 3 cards.
    - If the user closes the tab and then returns to the site, data is taken from local storage upon mounting the `App` component.
    - After the user has been authorized, the "Save" icon becomes active in the card block.
    - When clicking the "Save" icon in the card block, a request is made to the `/articles` route of the Practicum API.
    - When clicking on the active "Save" icon in the card block, a request to delete the card is made. After a successful request, the card is removed from the "Saved articles" page.
    _COMMENT_:
    **When saving the article by clicking on "Save", the article is not displayed in the saved articles page. When returning to the main page, article should be displayed with active "Save" icon(colored in blue), currently it doesn't stay active**
    - The "Saved articles" page displays the following: username, number of articles saved, and the keywords by which articles were found.
      _COMMENT_:
      **When a new user is logged in for the first time, there should be no saved articles on the page, now it currently shows 11 saved articles**
    - Card blocks in the "Saved articles" page contain the following: the keyword by which the card was found and the trash can icon for deleting the article.
- [ ]  No errors occur when building or running the project.
_COMMENT_:
**There is an error in console regarding no-unique keys: https://snipboard.io/Ba74AW.jpg, keys should be unique, here are some useful articles about this issue: https://reactjs.org/docs/lists-and-keys.html, https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318**
- [x]  The global state variable `currentUser` has been created.
- [ ]  Local storage: the interaction with the JWT token, the results of the search request, and the state variable are set up in the right order.
- Registration and authorization:
    - [x]  The `/saved-news` route is protected using the `ProtectedRoute` HOC component.
    - [ ]  When trying to access the `/saved-news` route, unauthorized users are redirected to `/signin` with an open authorization popup window.
    _COMMENT_:
    **Unauthorized users are not redirected to /signin and there is no popup window showing up, you need to implement it, so whenever unauthorized users try to access this route, they will be redirected to home page and prompted to authorize**
    - [x]  When an unauthorized user clicks on the icon to save an article, the registration popup window opens.
    - [x]  After successful authorization, the popup window is closed. A link to "Saved articles" and a logout button with the username appear in the header.
    - [x]  The `/` route is not protected.
    - [x]  After a successful `onSignOut()` handler call, the user is redirected to `/`.
    - [x]  The `useHistory()` hook is used correctly.
    - [x]  The components `<Switch />`, `<Route />`, and `<Redirect />` are used correctly.
- Components:
    - [x]  Hooks are not used inside conditional statements or loops.
    - [x]  For class components, effects are described inside the component lifecycle methods.
    - [x]  Hooks are called in a component's main function.
    - [x]  The `Main`, `NavBar`, and `SavedNewsHeader` components are subscribed to the `CurrentUserContext` context.
    - [x]  The context is embedded in the `App` component via `CurrentUserContext.Provider`.
    - [x]  The `currentUser` state variable is created in the `App` root component. This variable is used as a value of the context provider.
    - [x]  The necessary handlers are defined inside the `App` root component: `onRegister()`, `onLogin()`, and `onSignOut()`. These handlers are passed to the appropriate components: `Register.js`, `Login.js`, and `NavBar.js`.
    - [ ]  The popup components only contain the submit event handlers. Other handlers, such as `handleUpdateUser()`, are described inside the `App` component.
    _COMMENT_:
    **Most of the logic that should be describled in handlers in the App component is currently described outside of it, for example: handleRegisterSubmit, handleSigninSubmit and etc. functions that are currently desciribed in the PopupWithForm momponent, most of the logic could be moved to App component**
- [x]  Asynchronous API requests:
	- Requests can be made through the Fetch API or by using XMLHttpRequest.
	- Third-party libraries (such as axios or jQuery) are not used.
	- API requests are contained in separate files: `MainApi.js` and `NewsApi.js`.
	- The chain for processing promises ends with a `catch()` block.
	- The first `then()` handler returns `res.json`.
- [x]  Naming:
	- Function and variable names use camelCase.
	- Only nouns are used as variable names.
	- Plural nouns are used for `NodeList`.
	- Classes are named using nouns that begin with a capital letter.
	- The `const` keyword is used for variables that won't be changed directly.
	- Class names correspond with their content.
	- Names must not include inappropriate or unclear abbreviations.
- [x]  No third-party JavaScript libraries are used.
- [x]  The date parameters of requests to News API must be calculated automatically (7 days prior to the current date). We recommend converting the `from` parameter to a timestamp and vice versa.

### Best Practices

- [x]  The initial state of state variables contain the correct data type.
- [x]  The API request for information about the user and for the array of cards is made once during mounting.
- [x]  API requests are described inside the `App` component.
- [x]  Arrow functions are not passed as handler functions.
- [x]  API error handling:
    - [x]  The user receives a message in case of an error.
    - [x]  Form fields are blocked while requests are being sent.
- [x]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.

### Recommendations

- [x]  Semantically correct blocks are used for components.
- [x]  No `<div>` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [ ]  The code is clean and easy to understand:
    - The purpose of each listener callback is clear from its name.
    - There are no "magic numbers," i.e. all numeric values are assigned to variables.
    - Сonstants are described in the same scope in which the function is declared. Inside the function, the values of the constants are taken from the closure.
    _COMMENT_:
    **There are lots of conditional statements in the code that are used in place where it can be simplified, also there are some numeric values that are not stored as constants**

## Number of points: 59

**Comment by arinaward** [comment]
# Summary:
### Performance Criteria

- [ ]  The project functionality is fully implemented according to the current stage's requirements:
    - The preloader is visible and spinning during request execution. 
    - All project links and buttons are functioning. 
    - All forms are validated on the client side. 
    - When clicking on the "Sign up" button in the "Sign up" popup window, a request is sent to the `/signup` route, provided that all input fields have been filled in correctly. If the request is successful, a message is displayed.
    - When clicking on the "Sign up" button in the "Sign up" popup window, a request is sent to the `/signup` route, provided that all input fields have been filled in correctly. If the request is successful, a message is displayed.
    - When clicking on the "Sign in" button, provided that all input fields have been filled in correctly, a request is sent to the `/signin` route. If the request is successful, the popup is closed.
    - Both header states function correctly. If the user is not logged in, the header should have the "Sign in" button; and if the user is logged in, there should be no "Sign in" button. The "Saved articles" link, along with a log out button, should appear in its place.
    - Once the search form has been submitted successfully, a block with results appears. If nothing was found, the message "Nothing found" appears.
    - 3 cards are displayed in the results block. Clicking on the "Show more" button will render the next 3 cards.
    - If the user closes the tab and then returns to the site, data is taken from local storage upon mounting the `App` component.
    - After the user has been authorized, the "Save" icon becomes active in the card block.
    - When clicking the "Save" icon in the card block, a request is made to the `/articles` route of the Practicum API.
    - When clicking on the active "Save" icon in the card block, a request to delete the card is made. After a successful request, the card is removed from the "Saved articles" page.
    - The "Saved articles" page displays the following: username, number of articles saved, and the keywords by which articles were found.
    - Card blocks in the "Saved articles" page contain the following: the keyword by which the card was found and the trash can icon for deleting the article.
- [x]  No errors occur when building or running the project.
- [x]  The global state variable `currentUser` has been created.
- [ ]  Local storage: the interaction with the JWT token, the results of the search request, and the state variable are set up in the right order.
- Registration and authorization:
    - [x]  The `/saved-news` route is protected using the `ProtectedRoute` HOC component.
    - [ ]  When trying to access the `/saved-news` route, unauthorized users are redirected to `/signin` with an open authorization popup window.
    _COMMENT_:
    **Unauthorized users are not redirected to /signin and there is no popup window showing up, you need to implement it, so whenever unauthorized users try to access this route, they will be redirected to home page and prompted to authorize**
    - [x]  When an unauthorized user clicks on the icon to save an article, the registration popup window opens.
    - [x]  After successful authorization, the popup window is closed. A link to "Saved articles" and a logout button with the username appear in the header.
    - [x]  The `/` route is not protected.
    - [x]  After a successful `onSignOut()` handler call, the user is redirected to `/`.
    - [x]  The `useHistory()` hook is used correctly.
    - [x]  The components `<Switch />`, `<Route />`, and `<Redirect />` are used correctly.
- Components:
    - [x]  Hooks are not used inside conditional statements or loops.
    - [x]  For class components, effects are described inside the component lifecycle methods.
    - [x]  Hooks are called in a component's main function.
    - [x]  The `Main`, `NavBar`, and `SavedNewsHeader` components are subscribed to the `CurrentUserContext` context.
    - [x]  The context is embedded in the `App` component via `CurrentUserContext.Provider`.
    - [x]  The `currentUser` state variable is created in the `App` root component. This variable is used as a value of the context provider.
    - [x]  The necessary handlers are defined inside the `App` root component: `onRegister()`, `onLogin()`, and `onSignOut()`. These handlers are passed to the appropriate components: `Register.js`, `Login.js`, and `NavBar.js`.
    - [ ]  The popup components only contain the submit event handlers. Other handlers, such as `handleUpdateUser()`, are described inside the `App` component.
    _COMMENT_:
    **Most of the logic that should be describled in handlers in the App component is currently described outside of it, for example: handleRegisterSubmit, handleSigninSubmit and etc. functions that are currently desciribed in the PopupWithForm momponent, most of the logic could be moved to App component**
- [x]  Asynchronous API requests:
	- Requests can be made through the Fetch API or by using XMLHttpRequest.
	- Third-party libraries (such as axios or jQuery) are not used.
	- API requests are contained in separate files: `MainApi.js` and `NewsApi.js`.
	- The chain for processing promises ends with a `catch()` block.
	- The first `then()` handler returns `res.json`.
- [x]  Naming:
	- Function and variable names use camelCase.
	- Only nouns are used as variable names.
	- Plural nouns are used for `NodeList`.
	- Classes are named using nouns that begin with a capital letter.
	- The `const` keyword is used for variables that won't be changed directly.
	- Class names correspond with their content.
	- Names must not include inappropriate or unclear abbreviations.
- [x]  No third-party JavaScript libraries are used.
- [x]  The date parameters of requests to News API must be calculated automatically (7 days prior to the current date). We recommend converting the `from` parameter to a timestamp and vice versa.

### Best Practices

- [x]  The initial state of state variables contain the correct data type.
- [x]  The API request for information about the user and for the array of cards is made once during mounting.
- [x]  API requests are described inside the `App` component.
- [x]  Arrow functions are not passed as handler functions.
- [x]  API error handling:
    - [x]  The user receives a message in case of an error.
    - [x]  Form fields are blocked while requests are being sent.
- [x]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.

### Recommendations

- [x]  Semantically correct blocks are used for components.
- [x]  No `<div>` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [ ]  The code is clean and easy to understand:
    - The purpose of each listener callback is clear from its name.
    - There are no "magic numbers," i.e. all numeric values are assigned to variables.
    - Сonstants are described in the same scope in which the function is declared. Inside the function, the values of the constants are taken from the closure.
    _COMMENT_:
    **There are lots of conditional statements in the code that are used in place where it can be simplified, also there are some numeric values that are not stored as constants**

## Number of points: 62

**Comment by arinaward** [comment]
Hello! Glad to say that your project has been accepted. It was truly a pleasure to review your project. Keep up the great work! I wish you best of luck in your future projects 🌷

# Summary:
### Performance Criteria

- [x]  The project functionality is fully implemented according to the current stage's requirements:
    - The preloader is visible and spinning during request execution. 
    - All project links and buttons are functioning. 
    - All forms are validated on the client side. 
    - When clicking on the "Sign up" button in the "Sign up" popup window, a request is sent to the `/signup` route, provided that all input fields have been filled in correctly. If the request is successful, a message is displayed.
    - When clicking on the "Sign up" button in the "Sign up" popup window, a request is sent to the `/signup` route, provided that all input fields have been filled in correctly. If the request is successful, a message is displayed.
    - When clicking on the "Sign in" button, provided that all input fields have been filled in correctly, a request is sent to the `/signin` route. If the request is successful, the popup is closed.
    - Both header states function correctly. If the user is not logged in, the header should have the "Sign in" button; and if the user is logged in, there should be no "Sign in" button. The "Saved articles" link, along with a log out button, should appear in its place.
    - Once the search form has been submitted successfully, a block with results appears. If nothing was found, the message "Nothing found" appears.
    - 3 cards are displayed in the results block. Clicking on the "Show more" button will render the next 3 cards.
    - If the user closes the tab and then returns to the site, data is taken from local storage upon mounting the `App` component.
    - After the user has been authorized, the "Save" icon becomes active in the card block.
    - When clicking the "Save" icon in the card block, a request is made to the `/articles` route of the Practicum API.
    - When clicking on the active "Save" icon in the card block, a request to delete the card is made. After a successful request, the card is removed from the "Saved articles" page.
    - The "Saved articles" page displays the following: username, number of articles saved, and the keywords by which articles were found.
    - Card blocks in the "Saved articles" page contain the following: the keyword by which the card was found and the trash can icon for deleting the article.
- [x]  No errors occur when building or running the project.
- [x]  The global state variable `currentUser` has been created.
- [ ]  Local storage: the interaction with the JWT token, the results of the search request, and the state variable are set up in the right order.
- Registration and authorization:
    - [x]  The `/saved-news` route is protected using the `ProtectedRoute` HOC component.
    - [ ]  When trying to access the `/saved-news` route, unauthorized users are redirected to `/signin` with an open authorization popup window.
    _COMMENT_:
    **Unauthorized users are not redirected to /signin and there is no popup window showing up, you need to implement it, so whenever unauthorized users try to access this route, they will be redirected to home page and prompted to authorize**
    - [x]  When an unauthorized user clicks on the icon to save an article, the registration popup window opens.
    - [x]  After successful authorization, the popup window is closed. A link to "Saved articles" and a logout button with the username appear in the header.
    - [x]  The `/` route is not protected.
    - [x]  After a successful `onSignOut()` handler call, the user is redirected to `/`.
    - [x]  The `useHistory()` hook is used correctly.
    - [x]  The components `<Switch />`, `<Route />`, and `<Redirect />` are used correctly.
- Components:
    - [x]  Hooks are not used inside conditional statements or loops.
    - [x]  For class components, effects are described inside the component lifecycle methods.
    - [x]  Hooks are called in a component's main function.
    - [x]  The `Main`, `NavBar`, and `SavedNewsHeader` components are subscribed to the `CurrentUserContext` context.
    - [x]  The context is embedded in the `App` component via `CurrentUserContext.Provider`.
    - [x]  The `currentUser` state variable is created in the `App` root component. This variable is used as a value of the context provider.
    - [x]  The necessary handlers are defined inside the `App` root component: `onRegister()`, `onLogin()`, and `onSignOut()`. These handlers are passed to the appropriate components: `Register.js`, `Login.js`, and `NavBar.js`.
    - [ ]  The popup components only contain the submit event handlers. Other handlers, such as `handleUpdateUser()`, are described inside the `App` component.
    _COMMENT_:
    **Most of the logic that should be describled in handlers in the App component is currently described outside of it, for example: handleRegisterSubmit, handleSigninSubmit and etc. functions that are currently desciribed in the PopupWithForm momponent, most of the logic could be moved to App component**
- [x]  Asynchronous API requests:
	- Requests can be made through the Fetch API or by using XMLHttpRequest.
	- Third-party libraries (such as axios or jQuery) are not used.
	- API requests are contained in separate files: `MainApi.js` and `NewsApi.js`.
	- The chain for processing promises ends with a `catch()` block.
	- The first `then()` handler returns `res.json`.
- [x]  Naming:
	- Function and variable names use camelCase.
	- Only nouns are used as variable names.
	- Plural nouns are used for `NodeList`.
	- Classes are named using nouns that begin with a capital letter.
	- The `const` keyword is used for variables that won't be changed directly.
	- Class names correspond with their content.
	- Names must not include inappropriate or unclear abbreviations.
- [x]  No third-party JavaScript libraries are used.
- [x]  The date parameters of requests to News API must be calculated automatically (7 days prior to the current date). We recommend converting the `from` parameter to a timestamp and vice versa.

### Best Practices

- [x]  The initial state of state variables contain the correct data type.
- [x]  The API request for information about the user and for the array of cards is made once during mounting.
- [x]  API requests are described inside the `App` component.
- [x]  Arrow functions are not passed as handler functions.
- [x]  API error handling:
    - [x]  The user receives a message in case of an error.
    - [x]  Form fields are blocked while requests are being sent.
- [x]  Non-variable values (hard-coded constants) are named in all capital letters and stored in a separate configuration file.

### Recommendations

- [x]  Semantically correct blocks are used for components.
- [x]  No `<div>` or other unnecessary HTML tags are used for components that consist of single-level blocks.
- [ ]  The code is clean and easy to understand:
    - The purpose of each listener callback is clear from its name.
    - There are no "magic numbers," i.e. all numeric values are assigned to variables.
    - Сonstants are described in the same scope in which the function is declared. Inside the function, the values of the constants are taken from the closure.
    _COMMENT_:
    **There are lots of conditional statements in the code that are used in place where it can be simplified, also there are some numeric values that are not stored as constants**

## Number of points: 92

**Comment by lindakovacs** [comment]
@arinabarnett thank you so much for your feedback it is so valuable and it pointed me into the right direction to fix my project and pass it. It was such an awesome collaboration. I wish you all the best!

**Pull request merged**
